server:
  contextPath: /api
  port: 8089

management:
  security:
    enabled: false

spring:
  kafka:
    bootstrapServers: localhost:9092
    consumer:
      groupId: czyhandsome-command
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: net.mguenther.gtd.kafka.serialization.ItemEventDeserializer
      autoOffsetReset: earliest
      enableAutoCommit: false
      isolationLevel: read_committed
    listener:
      ackMode: MANUAL

gtd:
  topic: topic-czyhandsome

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    appname: gtd-es-command-side
    preferIpAddress: true
