#!/bin/bash

docker build -t wurstmeister/kafka kafka/
docker build -t zookeeper zookeeper
docker build -t czyhandsome/api-gateway ../gtd-api-gateway
docker build -t czyhandsome/discovery-service ../gtd-discovery-service
docker build -t czyhandsome/gtd-command-side ../gtd-command-side
docker build -t czyhandsome/gtd-query-side ../gtd-query-side
