version: '2'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 5
      KAFKA_CREATE_TOPICS: "topic-czyhandsome:5:1"
    ports:
      - "9092:9092"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
  discovery:
    image: czyhandsome/discovery-service
    ports:
     - "8761:8761"
    environment:
      eureka.instance.hostname: discovery
  gateway:
    image: czyhandsome/api-gateway
    links:
      - discovery
      - gtd-command-side
      - gtd-query-side
    ports:
      - "8765:8765"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
  gtd-command-side:
    image: czyhandsome/gtd-command-side
    links:
      - discovery
    ports:
     - "8090:8090"
    environment:
      SERVER_PORT: 8090
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
  gtd-query-side:
    image: czyhandsome/gtd-query-side
    links:
      - discovery
    ports:
     - "8089:8089"
    environment:
      SERVER_PORT: 8089
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
